Ethan
nighthawkcoders/platformer4x pull request #26
Opened 2024-12-09 22:16 UTC by ethanwong2008

This is Ethan's change. The change is applying a speed boost to the mushroom.

2024-12-09 23:52 UTC, Parallaxes commented
This seems to (correct me if I'm wrong) delete half of all of the documentation in these files. What's that about?

2024-12-10 00:02 UTC, Parallaxes requested changes
Documentation is eviscerated...

2024-12-10 21:50 UTC, Parallaxes approved these changes
Code LGTM, and most docs are retained. Approved!

2024-12-10 21:53 UTC, Shay-Robostrike1 approved these changes

2024-12-10 21:53 UTC, AdityaS-2010 approved these changes

2024-12-10 22:09 UTC, closed without merging